//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servico_cliente.wsphp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/soap/HelloExample", ConfigurationName="wsphp.HelloExamplePortType")]
    public interface HelloExamplePortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MyServicewsdl) of message GetProximoRequest does not match the default value (http://localhost/soap/HelloExample)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MyServicewsdl#GetProximo", ReplyAction="*")]
        Servico_cliente.wsphp.GetProximoResponse GetProximo(Servico_cliente.wsphp.GetProximoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MyServicewsdl) of message GetDadosRequest does not match the default value (http://localhost/soap/HelloExample)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MyServicewsdl#GetDados", ReplyAction="*")]
        Servico_cliente.wsphp.GetDadosResponse GetDados(Servico_cliente.wsphp.GetDadosRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MyServicewsdl) of message GetStatusRequest does not match the default value (http://localhost/soap/HelloExample)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MyServicewsdl#GetStatus", ReplyAction="*")]
        Servico_cliente.wsphp.GetStatusResponse GetStatus(Servico_cliente.wsphp.GetStatusRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MyServicewsdl) of message IfUltimoListaRequest does not match the default value (http://localhost/soap/HelloExample)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MyServicewsdl#IfUltimoLista", ReplyAction="*")]
        Servico_cliente.wsphp.IfUltimoListaResponse IfUltimoLista(Servico_cliente.wsphp.IfUltimoListaRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MyServicewsdl) of message GetProcessoOpenRequest does not match the default value (http://localhost/soap/HelloExample)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MyServicewsdl#GetProcessoOpen", ReplyAction="*")]
        Servico_cliente.wsphp.GetProcessoOpenResponse GetProcessoOpen(Servico_cliente.wsphp.GetProcessoOpenRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MyServicewsdl) of message GetCaminhoProcessRequest does not match the default value (http://localhost/soap/HelloExample)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MyServicewsdl#GetCaminhoProcess", ReplyAction="*")]
        Servico_cliente.wsphp.GetCaminhoProcessResponse GetCaminhoProcess(Servico_cliente.wsphp.GetCaminhoProcessRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:MyServicewsdl) of message InserirArqRequest does not match the default value (http://localhost/soap/HelloExample)
        [System.ServiceModel.OperationContractAttribute(Action="urn:MyServicewsdl#InserirArq", ReplyAction="*")]
        Servico_cliente.wsphp.InserirArqResponse InserirArq(Servico_cliente.wsphp.InserirArqRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProximo", WrapperNamespace="urn:MyServicewsdl", IsWrapped=true)]
    public partial class GetProximoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int ID;
        
        public GetProximoRequest() {
        }
        
        public GetProximoRequest(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProximoResponse", WrapperNamespace="urn:MyServicewsdl", IsWrapped=true)]
    public partial class GetProximoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetProximoResponse() {
        }
        
        public GetProximoResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDados", WrapperNamespace="urn:MyServicewsdl", IsWrapped=true)]
    public partial class GetDadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int ID;
        
        public GetDadosRequest() {
        }
        
        public GetDadosRequest(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDadosResponse", WrapperNamespace="urn:MyServicewsdl", IsWrapped=true)]
    public partial class GetDadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetDadosResponse() {
        }
        
        public GetDadosResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatus", WrapperNamespace="urn:MyServicewsdl", IsWrapped=true)]
    public partial class GetStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int ID;
        
        public GetStatusRequest() {
        }
        
        public GetStatusRequest(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStatusResponse", WrapperNamespace="urn:MyServicewsdl", IsWrapped=true)]
    public partial class GetStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public GetStatusResponse() {
        }
        
        public GetStatusResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IfUltimoLista", WrapperNamespace="urn:MyServicewsdl", IsWrapped=true)]
    public partial class IfUltimoListaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int inicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public int ultimo;
        
        public IfUltimoListaRequest() {
        }
        
        public IfUltimoListaRequest(int ID, int inicio, int ultimo) {
            this.ID = ID;
            this.inicio = inicio;
            this.ultimo = ultimo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IfUltimoListaResponse", WrapperNamespace="urn:MyServicewsdl", IsWrapped=true)]
    public partial class IfUltimoListaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public IfUltimoListaResponse() {
        }
        
        public IfUltimoListaResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProcessoOpen", WrapperNamespace="urn:MyServicewsdl", IsWrapped=true)]
    public partial class GetProcessoOpenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int ID;
        
        public GetProcessoOpenRequest() {
        }
        
        public GetProcessoOpenRequest(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetProcessoOpenResponse", WrapperNamespace="urn:MyServicewsdl", IsWrapped=true)]
    public partial class GetProcessoOpenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetProcessoOpenResponse() {
        }
        
        public GetProcessoOpenResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCaminhoProcess", WrapperNamespace="urn:MyServicewsdl", IsWrapped=true)]
    public partial class GetCaminhoProcessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int ID;
        
        public GetCaminhoProcessRequest() {
        }
        
        public GetCaminhoProcessRequest(int ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCaminhoProcessResponse", WrapperNamespace="urn:MyServicewsdl", IsWrapped=true)]
    public partial class GetCaminhoProcessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public GetCaminhoProcessResponse() {
        }
        
        public GetCaminhoProcessResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InserirArq", WrapperNamespace="urn:MyServicewsdl", IsWrapped=true)]
    public partial class InserirArqRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int id_dado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string caminho;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public int status;
        
        public InserirArqRequest() {
        }
        
        public InserirArqRequest(int ID, int id_dado, string caminho, int status) {
            this.ID = ID;
            this.id_dado = id_dado;
            this.caminho = caminho;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InserirArqResponse", WrapperNamespace="urn:MyServicewsdl", IsWrapped=true)]
    public partial class InserirArqResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public bool @return;
        
        public InserirArqResponse() {
        }
        
        public InserirArqResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloExamplePortTypeChannel : Servico_cliente.wsphp.HelloExamplePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloExamplePortTypeClient : System.ServiceModel.ClientBase<Servico_cliente.wsphp.HelloExamplePortType>, Servico_cliente.wsphp.HelloExamplePortType {
        
        public HelloExamplePortTypeClient() {
        }
        
        public HelloExamplePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloExamplePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloExamplePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloExamplePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Servico_cliente.wsphp.GetProximoResponse Servico_cliente.wsphp.HelloExamplePortType.GetProximo(Servico_cliente.wsphp.GetProximoRequest request) {
            return base.Channel.GetProximo(request);
        }
        
        public string GetProximo(int ID) {
            Servico_cliente.wsphp.GetProximoRequest inValue = new Servico_cliente.wsphp.GetProximoRequest();
            inValue.ID = ID;
            Servico_cliente.wsphp.GetProximoResponse retVal = ((Servico_cliente.wsphp.HelloExamplePortType)(this)).GetProximo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Servico_cliente.wsphp.GetDadosResponse Servico_cliente.wsphp.HelloExamplePortType.GetDados(Servico_cliente.wsphp.GetDadosRequest request) {
            return base.Channel.GetDados(request);
        }
        
        public string GetDados(int ID) {
            Servico_cliente.wsphp.GetDadosRequest inValue = new Servico_cliente.wsphp.GetDadosRequest();
            inValue.ID = ID;
            Servico_cliente.wsphp.GetDadosResponse retVal = ((Servico_cliente.wsphp.HelloExamplePortType)(this)).GetDados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Servico_cliente.wsphp.GetStatusResponse Servico_cliente.wsphp.HelloExamplePortType.GetStatus(Servico_cliente.wsphp.GetStatusRequest request) {
            return base.Channel.GetStatus(request);
        }
        
        public bool GetStatus(int ID) {
            Servico_cliente.wsphp.GetStatusRequest inValue = new Servico_cliente.wsphp.GetStatusRequest();
            inValue.ID = ID;
            Servico_cliente.wsphp.GetStatusResponse retVal = ((Servico_cliente.wsphp.HelloExamplePortType)(this)).GetStatus(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Servico_cliente.wsphp.IfUltimoListaResponse Servico_cliente.wsphp.HelloExamplePortType.IfUltimoLista(Servico_cliente.wsphp.IfUltimoListaRequest request) {
            return base.Channel.IfUltimoLista(request);
        }
        
        public bool IfUltimoLista(int ID, int inicio, int ultimo) {
            Servico_cliente.wsphp.IfUltimoListaRequest inValue = new Servico_cliente.wsphp.IfUltimoListaRequest();
            inValue.ID = ID;
            inValue.inicio = inicio;
            inValue.ultimo = ultimo;
            Servico_cliente.wsphp.IfUltimoListaResponse retVal = ((Servico_cliente.wsphp.HelloExamplePortType)(this)).IfUltimoLista(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Servico_cliente.wsphp.GetProcessoOpenResponse Servico_cliente.wsphp.HelloExamplePortType.GetProcessoOpen(Servico_cliente.wsphp.GetProcessoOpenRequest request) {
            return base.Channel.GetProcessoOpen(request);
        }
        
        public string GetProcessoOpen(int ID) {
            Servico_cliente.wsphp.GetProcessoOpenRequest inValue = new Servico_cliente.wsphp.GetProcessoOpenRequest();
            inValue.ID = ID;
            Servico_cliente.wsphp.GetProcessoOpenResponse retVal = ((Servico_cliente.wsphp.HelloExamplePortType)(this)).GetProcessoOpen(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Servico_cliente.wsphp.GetCaminhoProcessResponse Servico_cliente.wsphp.HelloExamplePortType.GetCaminhoProcess(Servico_cliente.wsphp.GetCaminhoProcessRequest request) {
            return base.Channel.GetCaminhoProcess(request);
        }
        
        public string GetCaminhoProcess(int ID) {
            Servico_cliente.wsphp.GetCaminhoProcessRequest inValue = new Servico_cliente.wsphp.GetCaminhoProcessRequest();
            inValue.ID = ID;
            Servico_cliente.wsphp.GetCaminhoProcessResponse retVal = ((Servico_cliente.wsphp.HelloExamplePortType)(this)).GetCaminhoProcess(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Servico_cliente.wsphp.InserirArqResponse Servico_cliente.wsphp.HelloExamplePortType.InserirArq(Servico_cliente.wsphp.InserirArqRequest request) {
            return base.Channel.InserirArq(request);
        }
        
        public bool InserirArq(int ID, int id_dado, string caminho, int status) {
            Servico_cliente.wsphp.InserirArqRequest inValue = new Servico_cliente.wsphp.InserirArqRequest();
            inValue.ID = ID;
            inValue.id_dado = id_dado;
            inValue.caminho = caminho;
            inValue.status = status;
            Servico_cliente.wsphp.InserirArqResponse retVal = ((Servico_cliente.wsphp.HelloExamplePortType)(this)).InserirArq(inValue);
            return retVal.@return;
        }
    }
}
